name: "JFrog CLI Github Example"
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: amd64/golang:latest
  
    steps:
    - name: setup JFrog CLI
      ##this step uses github cli action
      uses: jfrog/setup-jfrog-cli@v3
      with:
        version: latest
      env:
          # JFrog platform URL (for example: https://noyb.jfrog.io) 
          JF_URL: ${{ secrets.JF_URL }}
          # JFrog Platform access token
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
          #JF_ENV_TOKEN: ${{ secrets.JF_SECRET_ENV_TOKEN }}
        
      # This action checks out the code from the repository
    - name: Checkout Code
      uses: actions/checkout@v2
      
    - name: Connectivity test
      run: |
        export JFROG_CLI_LOG_LEVEL=DEBUG
        jf rt ping
        jf rt curl /api/system/version
        
    - name: Docker login
      run: |
         docker login $JF_URL



