name: "JFrog CLI Github Example"
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: amd64/golang:latest
  
    steps:
    - name: setup JFrog CLI
      #this step uses github cli action
      uses: jfrog/setup-jfrog-cli@v3
      with:
        version: latest
      env:
       JF_ENV_TOKEN: ${{ secrets.JF_SECRET_ENV_TOKEN }}
        
      # This action checks out the code from the repository
    - name: Checkout Code
      uses: actions/checkout@v2
      
    - name: Connectivity test
      run: |
        export JFROG_CLI_LOG_LEVEL=DEBUG
        jf rt ping
        jf rt curl /api/system/version
