name: "JFrog CLI Github Example"
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: amd64/golang:latest
  
    steps:
    - name: setup JFrog CLI
      #this step uses github cli action
      uses: jfrog/setup-jfrog-cli@v3
      with:
        version: latest
      env:
          # JFrog platform URL (for example: https://noyb.jfrog.io) 
          JF_URL: ${{ secrets.JF_URL }}
          # JFrog Platform access token
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
          #JF_ENV_TOKEN: ${{ secrets.JF_SECRET_ENV_TOKEN }}
        
      # This action checks out the code from the repository
    - name: Checkout Code
      uses: actions/checkout@v2
      
    - name: Connectivity test
      run: |
        export JFROG_CLI_LOG_LEVEL=DEBUG
        jf rt ping
        jf rt curl /api/system/version
        
    - name: Upload DEB file to Artifactory
      run: |
       
        #jf rt u --deb=bionic/main/all /Users/noyb/Downloads/ripgrep_13.0.0-2.1_amd64.deb debian-virtual-cli/pool/main/c/carbon/ripgrep_13.0.0-2.1_amd64.deb
        #jf rt u --deb=bionic/main/all "/Users/noyb/Downloads/carbon-relay-ng_0.9.3-1_amd64.deb" debian-virtual-cli/pool/main/c/carbon/carbon-relay-ng_0.9.3-1_amd64.deb
    
    - name: Sleep for 60s
      uses: juliangruber/sleep-action@v2.0.0
      with:
        time: 60s
    
    - name: Re-calculate index to the virtual repository
    #re-calculate index to the virtual repository before attempting to install the packages, you may use the Calculate Debian Repository Metadata REST API call:
      run: |
        jf rt curl -X POST /api/deb/reindex/debian-virtual-cli
    
    - name: Sleep for 60s
      uses: juliangruber/sleep-action@v2.0.0
      with:
        time: 60s
        
    - name: Download DEB file from Artifactory
      run: |
        #jf rt dl "debian-virtual-cli/pool/main/c/carbon/carbon-relay-ng_0.9.3-1_amd64.deb" /Users/noyb/Downloads/260357/
        jf rt dl "debian-virtual-cli/pool/main/c/carbon/ripgrep_13.0.0-2.1_amd64.deb" /Users/noyb/Downloads/260357/



