name: "JFrog CLI Github Example"
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: amd64/golang:latest
  
    steps:
    # This action checks out the code from the repository
    - name: Checkout Code
      uses: actions/checkout@v2
      

    - uses: jfrog/setup-jfrog-cli@v3
      env:
        # JFrog platform URL (for example https://noyb.jfrog.io) 
        JF_URL: ${{ secrets.JF_URL }}
        # JFrog Platform access token
        JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
    - run: |
        jf rt ping
